### PR TITLE
Add ruby library to list

### PR DESCRIPTION
**Pull request by sandstrom**
Update the 'language support' section on this website:
https://wasmtime.dev/

### CODE REVIEW

**Comment by sandstrom** [comment]
ping @K0R7 @fitzgen

**Review by fitzgen — COMMENTED** [review]
In `wasmtime/README.md` we mention the gem rather than the repo. IIUC, that is what users will care more about. Should we switch the wording here? If we want to reference the repo rather than the gem, then we should change `wasmtime/README.md` to match.

**Comment by sandstrom** [comment]
@fitzgen I've updated to what I think you are asking for.

**Review by fitzgen — APPROVED** [review]
Thanks! And sorry that this took an embarrassingly long time to merge :grimacing:

**Comment by fitzgen** [comment]
Merging this as part of #23. Thanks again!

**Pull request closed without merging**
